apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Release.Name }}-deployment

spec:
  selector:
    matchLabels:
      app: nginx

  replicas: {{ .Values.replicas}} # tells deployment to run 2 pods matching the template

  template:
    metadata:
      labels:
       app: nginx

    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80

