apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow
  labels:
    app: nginx
spec:
  storageClassName: gp2    #fetch using the get kc get sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi