apiVersion: v1
gcePersistentDisk: ~
kind: PersistentVolume
metadata: 
  name: test-volume
spec: 
  accessModes: 
    - ReadWriteOnce
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-0d27ad1bb7b309ce2        # map the volume created in UI
  capacity: 
    storage: 4Gi      # we can mention less than or equal to the storage volume created.
  storageClassName: fast   #any custom name