apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: test-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 4Gi   #can use the volume less than or equal to that was specified in pv
  storageClassName: fast  #should be the same name