apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow-1
  labels:
    app: nginx
spec:
  storageClassName: myownstorage    #fetch using the get kc get sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi