kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: myownstorage
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"  # this becomes deafulat sc if we give to true.
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4 