apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: spogaku
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sudheerp2005@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx

